#!/bin/bash
# Preinstall script for linux deb
# the deb installer expects a file named preinst
set -e
INSTALL_DIR="$1"
SCRIPT_DIR="$(dirname "$0")"

echo "Running Linux prepare.sh preinst script..."
bash "$SCRIPT_DIR/prepare.sh" "$INSTALL_DIR"
